### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by bloha** [rajce-client/promise-util#1]
# v1 Roadmap
- [ ] Add a Promise.race like function which will return remaining promises
- [ ] Add a generator that yields results as soon as possible
- [ ] Add a generator which will wrap another generator and will request the results of the generator before a request
